### PR TITLE
feat: support model serialize

### PR DESCRIPTION
**Pull request by eigmax**

### CODE REVIEW

**Review by leonardoalt — COMMENTED** [review]
Looks good, but why is it needed? Just asking because revme doesn't use it, since the contents are already json serialized in the test files

**Comment by eigmax** [comment]
I am building a standalone server: `executor`, the `executor` will keep producing `TestUnit` alike files and another proving service, the prover keeps consuming that.  I just reuse the `TestUnit` in models, and will change it to another serialization when we have tested E2E.

**Comment by leonardoalt** [comment]
Hey @eigmax I've fixed the code to work with new revm and podwr. Can you re-organize this branch to have only https://github.com/powdr-labs/powdr-revme/pull/3/commits/d8e52a1411e2b73270f1f189fff72244c6b007e3 ?

**Comment by eigmax** [comment]
Will submit by another PR.

**Pull request closed without merging**
